import { Language } from '../types/pdf';

export const INDIAN_LANGUAGES: Language[] = [
  {
    code: 'hi-IN',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in pure, polite Hindi using Devanagari script.',
    voiceCode: 'hi-IN',
  },
  {
    code: 'en-IN',
    name: 'English (India)',
    nativeName: 'English',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in clear, concise Indian English.',
    voiceCode: 'en-IN',
  },
  {
    code: 'hinglish',
    name: 'Hinglish',
    nativeName: 'Hinglish (Hindi in Roman)',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in conversational Hinglish (Hindi words typed in Roman script, e.g. "Is document mein important points hain...").',
    voiceCode: 'en-IN',
  },
  {
    code: 'ta-IN',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in Tamil script.',
    voiceCode: 'ta-IN',
  },
  {
    code: 'te-IN',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in Telugu script.',
    voiceCode: 'te-IN',
  },
  {
    code: 'bn-IN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in Bengali script.',
    voiceCode: 'bn-IN',
  },
  {
    code: 'mr-IN',
    name: 'Marathi',
    nativeName: 'मराठी',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in Marathi (Devanagari script).',
    voiceCode: 'mr-IN',
  },
  {
    code: 'gu-IN',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in Gujarati script.',
    voiceCode: 'gu-IN',
  },
  {
    code: 'kn-IN',
    name: 'Kannada',
    nativeName: 'கன்னட / ಕನ್ನಡ',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in Kannada script.',
    voiceCode: 'kn-IN',
  },
  {
    code: 'ml-IN',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    promptInstruction: 'Write the response in Malayalam script.',
    voiceCode: 'ml-IN',
  },
  {
    code: 'es-ES',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    promptInstruction: 'Write the response in natural Spanish.',
    voiceCode: 'es-ES',
  },
  {
    code: 'fr-FR',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    promptInstruction: 'Write the response in elegant French.',
    voiceCode: 'fr-FR',
  },
];
